In [4]:
# ============================================
# SECTION 1: CREATE AND LOAD INDIAN DATASET
# ============================================

import pandas as pd
import os

# Create a small Indian states dataset
data = {
    "State": [
        "Karnataka", "Tamil Nadu", "Kerala", "Maharashtra",
        "Gujarat", "Rajasthan", "Telangana", "Andhra Pradesh",
        "West Bengal", "Odisha"
    ],
    "Region": [
        "South", "South", "South", "West",
        "West", "North", "South", "South",
        "East", "East"
    ],
    "Population_Millions": [
        67.0, 76.0, 35.0, 126.0,
        70.0, 82.0, 38.0, 54.0,
        100.0, 46.0
    ],
    "Literacy_Percent": [
        75.4, 80.1, 94.0, 82.3,
        78.0, 66.1, 72.8, 67.4,
        76.3, 72.9
    ],
    "Area_sq_km": [
        191791, 130060, 38863, 307713,
        196024, 342239, 112077, 162968,
        88752, 155707
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save the dataset as CSV
df.to_csv("indian_states.csv", index=False)

# Load the CSV file using Pandas
df = pd.read_csv("indian_states.csv")

# Display basic information
print("Dataset loaded successfully!")
print("Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nFirst 10 rows:")
display(df.head(10))

Dataset loaded successfully!
Shape: (10, 5)

Data Types:
State                   object
Region                  object
Population_Millions    float64
Literacy_Percent       float64
Area_sq_km               int64
dtype: object

First 10 rows:

            State Region  Population_Millions  Literacy_Percent  Area_sq_km
0       Karnataka  South                 67.0              75.4      191791
1      Tamil Nadu  South                 76.0              80.1      130060
2          Kerala  South                 35.0              94.0       38863
3     Maharashtra   West                126.0              82.3      307713
4         Gujarat   West                 70.0              78.0      196024
5       Rajasthan  North                 82.0              66.1      342239
6       Telangana  South                 38.0              72.8      112077
7  Andhra Pradesh  South                 54.0              67.4      162968
8     West Bengal   East                100.0              76.3       88752
9          Odisha   East                 46.0              72.9      155707

In [5]:
# ============================================
# SECTION 2: FILTER AND GROUPBY
# ============================================

# FILTER:
# Select states having population greater than 60 million
filtered_df = df[df["Population_Millions"] > 60]

print("FILTER RESULT:")
display(filtered_df)

# GROUPBY:
# Group states by region and calculate average population
grouped_df = df.groupby("Region")["Population_Millions"].mean()

print("\nGROUPBY RESULT:")
display(grouped_df)

# GROUPBY with multiple statistics
region_summary = df.groupby("Region")["Population_Millions"].agg(
    ["count", "mean", "sum", "max"]
)

print("\nREGION SUMMARY:")
display(region_summary)

FILTER RESULT:

         State Region  Population_Millions  Literacy_Percent  Area_sq_km
0    Karnataka  South                 67.0              75.4      191791
1   Tamil Nadu  South                 76.0              80.1      130060
3  Maharashtra   West                126.0              82.3      307713
4      Gujarat   West                 70.0              78.0      196024
5    Rajasthan  North                 82.0              66.1      342239
8  West Bengal   East                100.0              76.3       88752

GROUPBY RESULT:

Region
East     73.0
North    82.0
South    54.0
West     98.0
Name: Population_Millions, dtype: float64

REGION SUMMARY:

        count  mean    sum    max
Region
East        2  73.0  146.0  100.0
North       1  82.0   82.0   82.0
South       5  54.0  270.0   76.0
West        2  98.0  196.0  126.0

In [6]:
# ============================================
# SECTION 3: MERGE AND PIVOT TABLE
# ============================================

# Create a second DataFrame containing additional state information
state_info = pd.DataFrame({
    "State": [
        "Karnataka", "Tamil Nadu", "Kerala", "Maharashtra",
        "Gujarat", "Rajasthan", "Telangana", "Andhra Pradesh",
        "West Bengal", "Odisha"
    ],
    "GDP_Index": [
        8.5, 9.2, 7.8, 12.5, 10.1,
        6.8, 8.0, 6.5, 7.2, 5.9
    ]
})

# MERGE:
# Combine the main DataFrame and state_info using the State column
merged_df = pd.merge(
    df,
    state_info,
    on="State",
    how="left"
)

print("MERGE RESULT:")
display(merged_df)

# PIVOT TABLE:
# Calculate average population for each region
pivot_table = pd.pivot_table(
    df,
    values="Population_Millions",
    index="Region",
    aggfunc="mean"
)

print("\nPIVOT TABLE RESULT:")
display(pivot_table)

MERGE RESULT:

,State,Region,Population_Millions,Literacy_Percent,Area_sq_km,GDP_Index
0,Karnataka,South,67.0,75.4,191791,8.5
1,Tamil Nadu,South,76.0,80.1,130060,9.2
2,Kerala,South,35.0,94.0,38863,7.8
3,Maharashtra,West,126.0,82.3,307713,12.5
4,Gujarat,West,70.0,78.0,196024,10.1
5,Rajasthan,North,82.0,66.1,342239,6.8
6,Telangana,South,38.0,72.8,112077,8.0
7,Andhra Pradesh,South,54.0,67.4,162968,6.5
8,West Bengal,East,100.0,76.3,88752,7.2
9,Odisha,East,46.0,72.9,155707,5.9

PIVOT TABLE RESULT:

        Population_Millions
Region
East                   73.0
North                  82.0
South                  54.0
West                   98.0

In [7]:
# ============================================
# SECTION 4: CLEAN AND EXPORT DATA
# ============================================

# Create a copy for cleaning
cleaned_df = df.copy()

# Remove duplicate rows
cleaned_df = cleaned_df.drop_duplicates()

# Remove rows containing missing values
cleaned_df = cleaned_df.dropna()

print("Cleaned DataFrame:")
display(cleaned_df)

print("\nCleaned DataFrame shape:", cleaned_df.shape)

# EXPORT TO CSV
cleaned_df.to_csv(
    "indian_states_cleaned.csv",
    index=False
)

print("\nCSV file created successfully!")

# Install PyArrow for Parquet support
!pip install pyarrow -q

# EXPORT TO PARQUET
cleaned_df.to_parquet(
    "indian_states_cleaned.parquet",
    index=False
)

print("Parquet file created successfully!")

Cleaned DataFrame:

            State Region  Population_Millions  Literacy_Percent  Area_sq_km
0       Karnataka  South                 67.0              75.4      191791
1      Tamil Nadu  South                 76.0              80.1      130060
2          Kerala  South                 35.0              94.0       38863
3     Maharashtra   West                126.0              82.3      307713
4         Gujarat   West                 70.0              78.0      196024
5       Rajasthan  North                 82.0              66.1      342239
6       Telangana  South                 38.0              72.8      112077
7  Andhra Pradesh  South                 54.0              67.4      162968
8     West Bengal   East                100.0              76.3       88752
9          Odisha   East                 46.0              72.9      155707

Cleaned DataFrame shape: (10, 5)

CSV file created successfully!
Parquet file created successfully!

In [8]:
# ============================================
# SECTION 4: CLEAN AND EXPORT DATA
# ============================================

# Create a copy for cleaning
cleaned_df = df.copy()

# Remove duplicate rows
cleaned_df = cleaned_df.drop_duplicates()

# Remove rows containing missing values
cleaned_df = cleaned_df.dropna()

print("Cleaned DataFrame:")
display(cleaned_df)

print("\nCleaned DataFrame shape:", cleaned_df.shape)

# EXPORT TO CSV
cleaned_df.to_csv(
    "indian_states_cleaned.csv",
    index=False
)

print("\nCSV file created successfully!")

# Install PyArrow for Parquet support
!pip install pyarrow -q

# EXPORT TO PARQUET
cleaned_df.to_parquet(
    "indian_states_cleaned.parquet",
    index=False
)

print("Parquet file created successfully!")

Cleaned DataFrame:

            State Region  Population_Millions  Literacy_Percent  Area_sq_km
0       Karnataka  South                 67.0              75.4      191791
1      Tamil Nadu  South                 76.0              80.1      130060
2          Kerala  South                 35.0              94.0       38863
3     Maharashtra   West                126.0              82.3      307713
4         Gujarat   West                 70.0              78.0      196024
5       Rajasthan  North                 82.0              66.1      342239
6       Telangana  South                 38.0              72.8      112077
7  Andhra Pradesh  South                 54.0              67.4      162968
8     West Bengal   East                100.0              76.3       88752
9          Odisha   East                 46.0              72.9      155707

Cleaned DataFrame shape: (10, 5)

CSV file created successfully!
Parquet file created successfully!